---
title: "Hans"
subtitle: "With flipbookr and xaringan"
author: "Gina Reynolds, December 2019"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [xaringan-themer.css]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F, dev = "svg", fig.ext = "svg", dev.args = list(bg = "transparent"))
library(flipbookr)
library(tidyverse)
library(gapminder)
```

---



```{r xaringan-themer, include = F}
xaringanthemer::style_mono_accent(
  # hex color should be provided, or theme_xaringan doesn't work
  base_color = '#ffa500', #orange
  title_slide_background_image = "hans_bbc.png",
  background_image = "hans_bbc.png",
  code_font_size = '14px',
  text_slide_number_color = '#b3b3b3', #grey70
  link_color = '#ff4500', #orangered  
  footnote_font_size = '0.5em',
  footnote_position_bottom = "30px",
  code_highlight_color = "#ffedcc", #faded-orange
  extra_css = list(
    ".pull-left-70" = list("float" = "left", "width" = "65.8%"),
    ".pull-right-30" = list("float" = "right", "width" = "28.2%"),
    ".pull-left-30" = list("float" = "left", "width" = "28.2%"),
    ".pull-right-70" = list("float" = "right", "width" = "65.8%"),
    ".orange" = list("color" = "#ffa500"),
    ".note" = list("font-size" = "0.8em", "position" = "absolute", 
      "bottom" = "30px", "padding-right" = "4em")
  )
)
```


---

https://www.youtube.com/watch?v=jbkSRLYSojo

---


```{r}
talk <- c("So, here we go",
"First an axis for health: life exectancy ...",
"And down here an axis for wealth: income per person ...") %>% 
  paste("### ", .)

```



---

`r chunk_reveal("build", display_type = "output")`


```{r build, include = T}
library(shadowtext)
library(gapminder)
gapminder %>% 
  filter(year == 2007) %>%
  arrange(-pop) %>%
  ggplot() + 
  theme(panel.background = element_rect(fill = "transparent")) +
  theme(plot.background = element_rect(fill = "transparent")) +
  theme(legend.position = "none") +
  theme(panel.grid = element_line(color = alpha("cyan1", .1))) +
  theme(axis.line = element_line(color = "cyan1")) +
  theme(axis.ticks =  element_line(color = "cyan1")) +
  theme(axis.text = element_text(color = alpha("cyan1", .5), size = 15, face = "bold")) +
  theme(line = element_line(color = alpha("cyan1", .1), 
                            size = 1.5)) +
  theme(axis.title = element_text(color = alpha("cyan1", .7), size = 30, face = "bold")) +
  theme(axis.title.y = element_text(hjust = 1, vjust = 0, size = 20)) +
  aes(y = lifeExp) +
  labs(y = "Life Span") +
  scale_y_continuous(breaks = 1:3*25, labels = paste(1:3*25, "\n", "years"),
                     expand = c(.1,.1), limits = c(25,80)) +
  theme(axis.title.x = element_text(hjust = 1, vjust = 0, size = 20)) +
  aes(x = gdpPercap) +
  labs(x = "income") +
  scale_x_log10(limits = c(300, 80000), 
                labels = c("$400", "$4 000", "$40 000"),
                breaks = c(400, 4000, 40000)) +
  aes(color = continent) +
  aes(size = pop^2) +
  scale_size(range = c(3, 12)) +
  geom_point(data = . %>% filter(continent == "Africa"),
             alpha = 1,
             alpha = 0, 
             shape = 21,
             color = "grey30",
             fill = "blue"
             ) +
  geom_point(data = . %>% filter(continent == "Americas"),
             shape = 21,
             color = "grey30",
             fill = "green") +
  geom_point(data = . %>% filter(continent == "Asia"),
             shape = 21,
             color = "grey30",
             fill = "red") +
  geom_point(data = . %>% filter(continent == "Europe"),
             shape = 21,
             color = "grey30",
             fill = "goldenrod") +
  geom_shadowtext(data = tibble(x = 500, y = 25, 
           label = "Poor &\nSick"), 
           aes(x = x, y= y , label = label, size = NULL),
           size = 10,
           color = "cyan3",
           alpha = .7,
           alpha = 0,
           bg.colour = "cyan1",
            lineheight = .8,
           hjust = 0, vjust = 0
           ) +
  geom_shadowtext(data = tibble(x = 40000, y = 80, 
           label = "Wealthy &\nHealthy"), 
           aes(x = x, y= y , label = label, size = NULL),
           size = 10,
           color = "cyan3",
           alpha = .7,
           alpha = 0,
           bg.colour = "cyan1",
                      lineheight = .8,
           hjust = 1, vjust = 1,
           ) +
  geom_text(data = . %>% distinct(year),
            aes(label = year, x = 40000, y = 25),
             face = "bold",
            size = 30,
            color = "cyan1", alpha = .5,
            hjust = .7, vjust = 0)
  
  

```


r chunk_reveal("build", display_type = c("md", "code", "output"), md = talk, break_type = "user")`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}
```
