---
title: "parsing deep dive"
subtitle: "that big pipeline for parsing"
author: "Gina Reynolds, December 2019"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup}
library(flipbookr)
library(tidyverse)
knitr::opts_chunk$set(fig.width = 6, message = F, warning = F, comment = "", cache = F)
```

```{r xaringan_look}
xaringanthemer::mono_accent(
  code_highlight_color = "rgba(255, 211, 0, .35)",
  base_color = "#03418A")
```




---

A lot of "moves" are made in the code_parse function... 

```{r}
flipbookr:::code_parse
```

You can also look at this function in the source file:

https://github.com/EvaMaeRey/flipbookr/blob/master/R/base_parse_reveal_xaringan.R

---

Now lets walk through this pipeline inside `code_parse`


---

`r chunk_reveal("the_code_parsing")`

```{r the_code_parsing, include=FALSE}
create_code() %>% 
  code_as_table() ->
raw_code_table
create_code() %>% 
  code_base_parse() %>% 
  base_parsed_count_parentheses() %>% 
dplyr::left_join(raw_code_table) %>%
    dplyr::mutate(code = ifelse(comment != "", stringr::str_remove(raw_code, comment), raw_code)) %>%
    dplyr::mutate(connector = stringr::str_extract(stringr::str_trim(code), "%>%$|\\+$|->$|%\\+%")) %>%
    dplyr::mutate(connector = tidyr::replace_na(connector, "")) %>%
    dplyr::mutate(non_seq = stringr::str_extract(comment, "#BREAK-?\\d+")) %>%
    dplyr::mutate(non_seq = stringr::str_extract(non_seq, "-?\\d+")) %>%
    dplyr::mutate(non_seq = as.numeric(non_seq)) %>%
    dplyr::mutate(non_seq = tidyr::replace_na(non_seq, 1)) %>%
    dplyr::mutate(comment = stringr::str_remove(comment, "#BREAK\\d+")) %>%
    dplyr::mutate(user = stringr::str_detect(comment, "#BREAK")) %>%
    dplyr::mutate(comment = stringr::str_remove(comment, "#BREAK")) %>%
    dplyr::mutate(code = stringr::str_remove(stringi::stri_trim_right(code), "%>%$|\\+$|->$|%\\+%")) %>%
    dplyr::mutate(auto = balanced_paren & balanced_curly & balanced_square &
                    code != "") %>%
    dplyr::select(line, raw_code, code, connector, comment, auto, user, non_seq)  
```







```{css, eval = TRUE, echo = F}
.remark-code{line-height: 1.5; font-size: 60%}
```