---
title: "A Very Minimal Flipbook"
author: "Gina Reynolds, August, 2020"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=F}
knitr::opts_chunk$set(fig.width = 6, message = F, warning = F, 
                      comment = "", cache = F)
library(flipbookr)
```

```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}
```

# Let's look at some tidyverse pipelines

```{r}
library(tidyverse)
```

---

`r chunk_reveal(chunk_name = "wrangling")`

```{r wrangling, include = F}
cars %>% 
  filter(speed > 18) ->
fast_cars
```

---

`r chunk_reveal(chunk_name = "plotting")`

```{r plotting, include = F}
fast_cars %>% 
  ggplot() +
  aes(x = speed) +
  aes(y = dist) +
  geom_point() +
  aes(color = dist) +
  scale_color_viridis_c()
```




```{css, eval = TRUE, echo = F}
.remark-code{line-height: 1.5; font-size: 90%}
```


