---
title: "A collection of Data Visualizations on COVID-19"
subtitle: ""
author: "Edited by Gina Reynolds, March 2020"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      beforeInit: "https://platform.twitter.com/widgets.js"
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r setup3, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scracth can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, 
                      warning = FALSE, comment = "", 
                      cache = F, fig.retina = 3)
library(flipbookr)
library(tidyverse)
```


# getting data

```{r, eval = F}
url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"

# if file hasn't already been downloaded, download
if (!file.exists("time_series_19-covid-Confirmed-2020-03-19.csv")){
download.file(url, 
              destfile = 
                "time_series_19-covid-Confirmed-2020-03-19.csv") 
  } # 2020-03-19
```



---


`r chunk_reveal("data_prep")`

```{r data_prep, include=F}
library(tidyverse)

read_csv("time_series_19-covid-Confirmed-2020-03-19.csv") %>%
  gather(key = "date", 
         value = "num_cases",
         5:ncol(.))  %>%
  mutate(date = lubridate::mdy(date)) %>%
  janitor::clean_names() %>% 
  filter(country_region != "Cruise Ship") %>% 
  group_by(country_region, date) %>% 
  summarize(num_cases = sum(num_cases)) ->
data_long

data_long %>% 
  group_by(country_region) %>% 
  summarize(max_cases = max(num_cases)) %>% 
  arrange(-max_cases) %>% 
  slice(1:20) ->
top_20
```

`r chunk_reveal("data_plot")`

```{r data_plot, include=F}
options(scipen = 10)
top_20 %>% 
  left_join(data_long) %>% 
  ggplot() +
  aes(x = date) +
  aes(y = num_cases) +
  geom_line() +
  aes(group = country_region) +
  scale_y_log10() +
  scale_y_log10(breaks = c(1,10,100,1000, 10000, 100000)) +
  scale_y_log10(breaks = c(1,10,100,1000, 10000, 100000),
                limits = c(100, 100000)) ->
g

data_long %>% 
  filter(num_cases > 100) %>% 
  group_by(country_region) %>% 
  mutate(first_data_w_100 = min(date)) %>%
  mutate(days_since_100 = date - first_data_w_100) ->
data_long_since_100

g %+%
  (top_20 %>% 
  left_join(data_long_since_100)) +
  aes(x = days_since_100) +
  theme_minimal() +
  facet_wrap(~ country_region) +
  geom_line(data = . %>%
              mutate(country_region2 = country_region) %>% 
              select(-country_region),
            aes(group = country_region2),
            color = "grey") +
  geom_line(color = "magenta")
```



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 60%}
```
