---
title: "A collection of COVID-19 Data Visualization"
subtitle: ""
author: "Edited by Gina Reynolds, March 2020"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      beforeInit: "https://platform.twitter.com/widgets.js"
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r setup, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scracth can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, 
                      warning = FALSE, comment = "", 
                      cache = T, fig.retina = 3)
library(flipbookr)
library(tidyverse)
```

---


<!-- #geom_segment(aes(xend = end_date, yend = positive), linetype = 2, colour = 'grey') + -->
<!--   #geom_text(aes(x = end_date + 0.1, y = positive, -->
<!--                # label = state), hjust = 0) + -->

---

`r chunk_reveal(chunk_name = "peter")`


```{r peter, include = F}
covid19us::get_states_current() %>% 
  arrange(desc(positive)) %>% 
  slice(1:10) %>% 
  pull(state) ->
top10states

covid19us::get_states_daily()[1,1] %>% 
  pull() ->
end_date

covid19us::get_states_daily() %>%
  replace_na(list(positive = 0)) %>%
  select(date, state, positive, death) %>%
  filter(state %in% c(top10states)) %>%
  mutate(state = factor(state, levels = top10states)) %>%
  ggplot() +
  aes(x = date) + 
  aes(y = positive) +
  geom_point() +
  aes(color = state) +
  geom_line() +
  scale_color_viridis_d() +
  theme_linedraw(base_size = 14) +
  theme(legend.position = c(0.2, 0.8)) +
  guides(col = guide_legend(ncol = 2)) +
  labs(color = NULL) +
  labs(title = "Growth of COVID-19 Cases in\nTop 10 US States") +
  labs(x = "Date") + 
  labs(y = "Cases") + 
  labs(caption = "Data from the COVID Tracking Project API\nVia the covid19us package by Amanda Dobbyn") +
  gganimate::transition_reveal(date) +
  labs(title = "Logarithmic Growth of COVID-19 Cases in\nTop 10 US States") +
  scale_y_log10()
```

---

`r chunk_reveal(chunk_name = "peter_map")`

https://www.michigan.gov/coronavirus/0,9753,7-406-98163-520743--,00.html

```{r peter_map, include = F}
# coronavirus data ----
# scraping from state website - new data between 2-3 PM EDT each day
xml2::read_html("michigan.htm") ->
mi_corona
  
#clean data to a table
mi_corona %>%
  rvest::html_nodes('table') %>%
  rvest::html_table() ->
data

# clean up corona data ----
data[1] %>%
  as.data.frame() %>%
  filter( X1 != "County") %>%
  filter( X1 != "Out of State") %>%
  filter( X1 != "Not Reported") %>%
  filter( X1 != "Total") %>%
  purrr::set_names("county", "cases", "deaths") %>%
  as_tibble() %>%
  mutate(cases = as.numeric(cases),
         deaths = as.numeric(deaths)) ->
mi_corona2
```

---

`r chunk_reveal(chunk_name = "peter_map2")`


```{r peter_map2, include = F}
# Detroit City and Wayne county have separate health departments
# for goofy historical reasons - will combine into Wayne County
mi_corona2 %>% 
  filter(county == "Detroit City" |
           county == "Wayne") %>%
  summarize(cases = sum(cases),
            deaths = sum(deaths)) %>%
  mutate(county = "Wayne") %>%
  select(county, cases, deaths) ->
wayne

mi_corona2 %>%
  filter(county != "Detroit City" &
           county != "Wayne") %>%
  bind_rows(wayne) %>%
  arrange(county) %>%
  print(n = Inf) ->
mi_corona3
```

---

`r chunk_reveal(chunk_name = "peter_map3")`


```{r peter_map3, include = F}
options(tigris_use_cache = TRUE)
# tidycensus to get county geometries
tidycensus::census_api_key("a52a66fe882483b778a5dc1aa002051abba883fa")
tidycensus::get_acs(state = "MI", 
        geography = "county",
                    variables = "B19013_001", 
                    geometry = TRUE) ->
  michigan

# trim off " County, Michigan" from county names
michigan2 <- michigan %>%
  mutate(county = str_sub(NAME,
                          start = 1L,
                          end = str_locate(michigan$NAME, " County, Michigan")[,1])) %>%
  mutate(county = str_trim(county)) 
```


---

`r chunk_reveal(chunk_name = "peter_map4")`


```{r peter_map4, include = F}
options(scipen = 5)  
michigan2 %>%  
  select(county, geometry) %>%  
  left_join(mi_corona3) %>%  
  mutate(cases = replace_na(cases, 0.1)) ->  
joined  

joined %>%  
  ggplot() +  
  geom_sf(color = "grey98",  
          size = 0.005) +  
  aes(fill = cases) +  
  scale_fill_gradientn(colours = rev(heat.colors(7)),  
                       trans = "log10",  
                       breaks = c(.1,1,10,100, 1000)) +  
  geom_sf_text(aes(label = round(cases)),  
               col = "black",  
               size = 2) +  
  labs(fill = NULL) +
  theme_void() +  
  theme(plot.background = element_rect(fill = "grey98")) +
  theme(legend.position = c(0.30, 0.3)) +  
  labs(title = " Michigan COVID-19, Number of Cases by County 2020-Mar-25") +  
  labs(subtitle = " Data: https://www.michigan.gov/coronavirus | geography: US Census") +
  labs(caption = "Vis: Peter Higgins ")
```


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 60%}
```
