---
title: "'The Office' IMDb ratings"
subtitle: "for #TidyTuesday"
author: "Gina Reynolds, March 2020"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r setup, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scracth can be time consuming
knitr::opts_chunk$set(fig.width = 8, message = FALSE, warning = FALSE, comment = "", cache = T, fig.retina = 3)
library(flipbookr)
```




`r chunk_reveal("scan_in")`

```{r scan_in, include = F}
library(tidyverse)
url <- 'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-17/office_ratings.csv'
readr::read_csv(url) ->
  office_ratings
```

---

`r chunk_reveal("plot1")`

```{r plot1, include=F}
library(ggrepel)
office_ratings %>% 
  ggplot() +
  aes(x = air_date) +
  aes(y = imdb_rating) +
  geom_rect(data = office_ratings %>% filter(episode == 1),
            fill = "grey",
            xmin = min(office_ratings$air_date) - 60,
            ymin = 5, ymax = 10, alpha = .2,
            aes(xmax = air_date - 60)) +
  geom_point(shape = 21) +
  aes(fill = episode) +
  aes(size = total_votes) +
  scale_y_continuous(limits = c(5,10), expand = c(0,0)) +
  scale_fill_viridis_c(option = "cividis") +
  labs(x = NULL) + 
  labs(y = "Rating") +
  labs(size = "Total votes:") +
  labs(fill = "Episode:") +
  labs(title = "IMDb Episode Ratings for 'The Office' over its Nine Year Run") +
  labs(subtitle = "Data available on data.world") +
  labs(caption = "Viz: @EvaMaeRey for #TidyTuesday") +
  theme_minimal(base_family = "Courier",
                base_size = 12) +
  theme(plot.background = element_rect(fill = "grey98", 
                                       color = "grey90")) +
  theme(legend.position = c(.35, .1)) +
  theme(legend.direction = "horizontal") +
  theme(panel.grid = element_line("grey95")) +
  theme(plot.title.position = "plot") +
  geom_vline(data = office_ratings %>% 
               filter(episode == 1),
             linetype = "dashed",
             color = "darkgrey",
             aes(xintercept = air_date - 60)) +
  aes(label = title) +
  ggpmisc::stat_dens2d_filter(geom = "text_repel", 
                              keep.fraction = 0.25, 
                              size = 2.8, 
                              col = "grey30") +  
  geom_text(data = office_ratings %>% filter(episode == 1),
            aes(label = paste0(c("Season ", rep("", 8)), season),
                x = air_date),
            hjust = 1, angle = 90, family = "Courier",
            y = 9.9, size = 5, color = "#00022E") ->
g1
```

---

`r chunk_reveal("plot2")`


```{r plot2, include=F}
office_ratings %>% 
  sample_frac(size = 1, replace = F) %>% 
  ggplot() +
  aes(x = total_votes) +
  aes(y = imdb_rating) +
  geom_point(shape = 21) +
  aes(fill = season) +
  scale_fill_viridis_c(option = "cividis") +
  scale_y_continuous() +
  scale_x_log10() +
  labs(title = "IMDb Votes vs. Ratings for 'The Office' Episodes") +
  labs(subtitle = "Data available on data.world") +
  labs(caption = "Viz: @EvaMaeRey for #TidyTuesday") +
  labs(x = "Total Votes") +
  labs(y = "Rating") +
  aes(size = 3) +
  aes(label = title) +
  ggpmisc::stat_dens2d_filter(geom = "text_repel", 
                              keep.fraction = 0.25, 
                              size = 2.8, 
                              col = "grey30") +
  scale_size_identity() +  
  theme_minimal(base_family = "Courier",
                base_size = 12) +
  theme(plot.title.position = "plot") +
  theme(legend.position = c(.85, .35)) +
  theme(legend.background = element_rect(fill = "grey98", 
                                       color = "grey90")) +
  theme(plot.background = element_rect(fill = "grey98", 
                                       color = "grey90")) ->
g2
```


---

`r chunk_reveal("schrute")`


```{r schrute, include = F}
schrute::theoffice %>% 
  filter(season == "01" & episode == "01" ) %>% 
  mutate(character = ifelse(character == "Michel", 
                            "Michael", 
                            character)) %>% 
  filter(character != "Man") %>% 
  mutate(character_lag = lag(character)) %>% 
  select(character, character_lag) %>% 
  slice(-1) %>% 
  filter(character != character_lag) %>% 
  igraph::graph_from_data_frame() %>% 
  tidygraph::as_tbl_graph(graph) %>% 
  tidygraph::activate(nodes) %>%
  mutate(degree = tidygraph::centrality_degree()) %>% 
  ggraph::ggraph(layout = "kk", ) +
  theme_void(base_family = "Courier") +
  theme(plot.background = element_rect(fill = "steelblue4", 
                                       color = "grey90")) +
  ggraph::geom_edge_fan(alpha = .15,
                        color = "orange") +
  ggraph::geom_node_point(shape = 21,
                          fill = "grey80",
                          color = "grey50",
                          aes(size = degree, 
                              color = degree)) +
  ggraph::geom_node_text(nudge_y = .15,
                         aes(label = name),
                         color = "grey90",
                         family = "Courier") +
  labs(title = " Season 1, Episode 1 of 'The Office', Who (likely) speaks with whom ...") +
  theme(text = element_text(color = "grey90")) +
  labs(subtitle = " Connection drawn for temporally adjacent speakers") +
  labs(caption = "Viz: @EvaMaeRey for #TidyTuesday | Data: Schute package in R ") +
  labs(size = "Degree\nCentrality") +
  theme(legend.position = c(.85,.2)) ->
office_chats_s1_e1
```

---

```{r}
schrute::theoffice %>% 
  filter(season == "01") %>% 
  mutate(character = ifelse(character == "Michel", 
                            "Michael", 
                            character)) %>% 
  filter(character != "Man") %>% 
  mutate(character_lag = lag(character)) %>% 
  select(character, character_lag) %>% 
  slice(-1) %>% 
  filter(character != character_lag) %>% 
  igraph::graph_from_data_frame() %>% 
  tidygraph::as_tbl_graph(graph) %>% 
  tidygraph::activate(nodes) %>%
  mutate(degree = tidygraph::centrality_degree())  %>% 
  ggraph::ggraph(layout = "kk", ) +
  theme_void(base_family = "Courier") +
  theme(plot.background = element_rect(fill = "steelblue4", 
                                       color = "grey90")) +
  ggraph::geom_edge_fan(alpha = .15,
                        color = "orange") +
  ggraph::geom_node_point(shape = 21,
                          fill = "grey80",
                          color = "grey50",
                          aes(size = degree, 
                              color = degree)) +
  ggraph::geom_node_text(nudge_y = .15,
                         aes(label = name),
                         color = "grey90",
                         family = "Courier") +
  labs(title = " Season 1, Episode 1 of 'The Office', Who (likely) speaks with whom ...") +
  theme(text = element_text(color = "grey90")) +
  labs(subtitle = " Connection drawn for temporally adjacent speakers") +
  labs(caption = "Viz: @EvaMaeRey for #TidyTuesday | Data: Schute package in R ") +
  labs(size = "Degree\nCentrality") +
  theme(legend.position = c(.85,.2)) +
  facet_wrap()
```







```{r patch, eval = F, echo = F}
g1 +
  labs(title = NULL) +
  labs(subtitle = NULL) +
  labs(caption = NULL) ->
  g1
g2 +
  labs(title = NULL) +
  labs(subtitle = NULL) +
  labs(caption = NULL) ->
  g2
library(patchwork)
(g1 + g2) /
  g3

```

---


```{r}
library(ggraph)
iris[, 1:4] %>% 
  dist() %>% 
  hclust() %>% 
  ggraph() +
  geom_edge_bend2()  +
  geom_node_point(aes(filter = leaf)) +
  coord_polar(theta = "x") +
  scale_y_reverse()
```


---

```{r}
tidygraph::create_notable('zachary') %>% 
  mutate(clique = tidygraph::group_infomap()) %>% 
  mutate(clique = as.factor(clique)) %>% 
  ggraph() +
  geom_edge_link() +
  geom_node_point(aes(color = clique),
                  size = 4) +
  ggforce::geom_mark_hull(aes(x = x, y = y, 
                              fill = clique, 
                              color = clique),
                          linetype = "dashed")
```

---

```{r}
library(dendextend)
library(circlize)
par(mar = rep(0,4))

par(mar = rep(0,4))

# modify the dendrogram to have some colors in the branches and labels
datasets::mtcars %>% 
  dist() %>% 
  hclust() %>% 
  as.dendrogram() %>% 
   dendextend::color_branches(k = 4) %>% 
    color_labels %>% 
  dendextend::circlize_dendrogram(dend_track_height = 0.8) 

datasets::mtcars %>% 
  dist() %>% 
  hclust() %>% 
  ggraph() +
  geom_edge_bend() +
  geom_node_point(aes(filter = leaf)) +
  coord_polar(theta = "x") +
  scale_y_reverse() + 
  geom_node_text(aes(x = x*1.05, y=y*1.05, filter=leaf, 
                 angle = node_angle(x, y), label = label), 
             size=3, hjust='outward') +
  geom_node_text(aes(x = x*1.005, y=y*1.005, filter=leaf, 
                     angle = -((-node_angle(x, y)+90)%%180)+90, label = label), 
                 size=3, hjust='outward')


datasets::mtcars %>% 
  dist() %>% 
  hclust() %>%
ggraph(layout = 'dendrogram', 
       repel = TRUE, 
       circular = TRUE, 
       ratio = 0.5) + 
  geom_edge_elbow() + 
  geom_node_text(aes(x = x*1.005, y=y*1.005, filter=leaf, 
                     angle = -((-node_angle(x, y)+90)%%180)+90, label = label), 
                 size=3, hjust='outward') + 
  geom_node_point(aes(filter=leaf)) + 
  coord_fixed() + 
  ggforce::theme_no_axes()
```




---
class: center, middle

This presentation was created with the new {flipbookr} package and with {xaringan}.   Info: https://evamaerey.github.io/flipbooks/about. Install  `remotes::install_github("EvaMaeRey/flipbookr")`. 


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 45%}
```
